### ISSUE TITLE
Null pointer exception adding admin user on first run

### ISSUE THREAD

**Issue by tmyroadctfig** [thomasdarimont/spring-boot-keycloak-server-example#18]
I'm seeing a null pointer exception on the first run when it tries to add the admin user. Restarting the server seems to fix the issue (the admin user is added successfully). Here's the log:
`2020-04-11 23:49:14.876  WARN 87956 --- [  restartedMain] c.g.t.k.e.EmbeddedKeycloakApplication    : Couldn't create keycloak master admin user: null`

And  the stack trace:
```
java.lang.NullPointerException
	at org.keycloak.models.jpa.JpaUserProvider.getUsersCount(JpaUserProvider.java:600)
	at org.keycloak.storage.UserStorageManager.getUsersCount(UserStorageManager.java:453)
	at org.keycloak.models.cache.infinispan.UserCacheSession.getUsersCount(UserCacheSession.java:545)
	at org.keycloak.models.cache.infinispan.UserCacheSession.getUsersCount(UserCacheSession.java:550)
	at org.keycloak.services.managers.ApplianceBootstrap.createMasterRealmUser(ApplianceBootstrap.java:98)
	at com.github.thomasdarimont.keycloak.embedded.EmbeddedKeycloakApplication.tryCreateMasterRealmAdminUser(EmbeddedKeycloakApplication.java:55)
	at com.github.thomasdarimont.keycloak.embedded.EmbeddedKeycloakApplication.<init>(EmbeddedKeycloakApplication.java:37)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.jboss.resteasy.core.ConstructorInjectorImpl.construct(ConstructorInjectorImpl.java:152)
	at org.jboss.resteasy.spi.ResteasyProviderFactory.createProviderInstance(ResteasyProviderFactory.java:2784)
	at org.jboss.resteasy.spi.ResteasyDeployment.createApplication(ResteasyDeployment.java:364)
	at org.jboss.resteasy.spi.ResteasyDeployment.startInternal(ResteasyDeployment.java:277)
	at org.jboss.resteasy.spi.ResteasyDeployment.start(ResteasyDeployment.java:89)
	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.init(ServletContainerDispatcher.java:119)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.init(HttpServletDispatcher.java:36)
	at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1134)
	at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:986)
	at org.springframework.boot.web.embedded.tomcat.TomcatEmbeddedContext.load(TomcatEmbeddedContext.java:82)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270)
	at java.util.TreeMap$ValueSpliterator.forEachRemaining(TreeMap.java:2897)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.springframework.boot.web.embedded.tomcat.TomcatEmbeddedContext.lambda$deferredLoadOnStartup$0(TomcatEmbeddedContext.java:65)
	at org.springframework.boot.web.embedded.tomcat.TomcatEmbeddedContext.doWithThreadContextClassLoader(TomcatEmbeddedContext.java:106)
	at org.springframework.boot.web.embedded.tomcat.TomcatEmbeddedContext.deferredLoadOnStartup(TomcatEmbeddedContext.java:64)
	at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.performDeferredLoadOnStartup(TomcatWebServer.java:301)
	at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.start(TomcatWebServer.java:200)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.startWebServer(ServletWebServerApplicationContext.java:297)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.finishRefresh(ServletWebServerApplicationContext.java:163)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:553)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)
	at com.github.thomasdarimont.keycloak.embedded.EmbeddedKeycloakServer.main(EmbeddedKeycloakServer.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)
2020-04-11 23:49:14.820  WARN 87956 --- [l-1 housekeeper] com.zaxxer.hikari.pool.HikariPool        : HikariPool-1 - Thread starvation or clock leap detected (housekeeper delta=1m40s224ms418µs100ns).
```

Any pointers would be appreciated.

**Comment by YannPerthuis** [comment]
Looking at the logs I realized that the `tryCreateMasterRealmAdminUser` method is invoked long before the keycloak initialization creates the realm master. Then adding the admin user to the realm master inevitably fails.

To temporarily resolve the problem I overrided the `migrateAndBootstrap` method in the `EmbeddedKeycloakApplication` class to execute the steps this time in the correct order.

Is this the right way @thomasdarimont ? Thank you

Namely that I work with the [new repo](https://github.com/thomasdarimont/embedded-spring-boot-keycloak-server) and that I encountered the same error.

```java
public class EmbeddedKeycloakApplication extends KeycloakApplication {

    [...]

    public EmbeddedKeycloakApplication(@Context ServletContext context) {
        Resteasy.pushContext(ServletContext.class, augmentToRedirectContextPath(context));
    }

    @Override
    protected ExportImportManager migrateAndBootstrap() {
        final ExportImportManager exportImportManager = super.migrateAndBootstrap();
        tryCreateMasterRealmAdminUser();
        tryImportRealm();
        return exportImportManager;
    }

    [...]
```

**Comment by thomasdarimont** [comment]
@Lamapeuf and @tmyroadctfig Thanks for reporting this issue.

This repository is now superseded by [embedded-spring-boot-keycloak-server](https://github.com/thomasdarimont/embedded-spring-boot-keycloak-server)

I just fixed this with this [commit](https://github.com/thomasdarimont/embedded-spring-boot-keycloak-server/commit/18d42bbf88b31bb32ba58ad97bad78163b684be5) to the new repository.
